/**
 * Supabase Database type — GENERATED by scripts/generate-db-types.mjs from
 * supabase/migrations. Do not edit by hand: change a migration, then run
 * `TEST_DATABASE_URL=… npm run db:types`. tests/db/schema-types.test.mjs
 * fails if this file and the migrations disagree.
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

export type TodoComment = { agent: string; text: string; at: string }

export type AffiliateLinksRow = {
  id: string
  workspace_id: string
  character_id: string | null
  program: string
  merchant: string | null
  destination_url: string
  tracking_url: string | null
  code: string | null
  commission_type: 'percent' | 'fixed' | 'hybrid' | 'unknown'
  commission_rate: number | null
  disclosure_text: string
  status: 'active' | 'paused' | 'expired'
  created_at: string
  updated_at: string
}

export type AgentApprovalsRow = {
  id: string
  workspace_id: string
  character_id: string | null
  action_type: 'publish_content' | 'send_external_message' | 'brand_outreach' | 'change_social_credentials' | 'financial_action' | 'change_publishing_policy' | 'engagement_reply' | 'memory_update' | 'agent_task'
  entity_type: string
  entity_id: string | null
  title: string
  summary: string | null
  payload: Json
  risk_level: 'low' | 'medium' | 'high'
  status: 'DRAFT' | 'AWAITING_APPROVAL' | 'APPROVED' | 'REJECTED' | 'EXECUTING' | 'COMPLETED' | 'FAILED'
  requested_by_type: 'user' | 'agent' | 'system'
  requested_by_user: string | null
  requested_by_agent_id: string | null
  agent_run_id: string | null
  decided_by: string | null
  decided_at: string | null
  decision_note: string | null
  executed_at: string | null
  completed_at: string | null
  result: Json | null
  error: string | null
  expires_at: string | null
  idempotency_key: string | null
  created_at: string
  updated_at: string
}

export type AgentRunEventsRow = {
  id: string
  workspace_id: string
  agent_run_id: string
  seq: number
  type: 'message' | 'tool_call' | 'tool_result' | 'decision' | 'policy_block' | 'error'
  payload: Json
  created_at: string
}

export type AgentRunsRow = {
  id: string
  workspace_id: string
  agent_task_id: string
  agent_id: string
  character_id: string
  status: 'running' | 'succeeded' | 'failed' | 'cancelled' | 'budget_exceeded' | 'policy_blocked'
  model: string | null
  input_tokens: number
  output_tokens: number
  cost_usd: number
  output: Json | null
  error: string | null
  started_at: string
  finished_at: string | null
  created_at: string
}

export type AgentTasksRow = {
  id: string
  workspace_id: string
  character_id: string
  agent_id: string
  parent_task_id: string | null
  created_by_agent_id: string | null
  created_by_user: string | null
  type: string
  title: string
  input: Json
  priority: 'low' | 'medium' | 'high' | 'critical'
  status: 'proposed' | 'pending' | 'queued' | 'running' | 'awaiting_approval' | 'completed' | 'failed' | 'cancelled'
  requires_approval: boolean
  approved_by: string | null
  approved_at: string | null
  scheduled_for: string | null
  attempts: number
  max_attempts: number
  last_error: string | null
  result: Json | null
  idempotency_key: string | null
  created_at: string
  updated_at: string
  approval_id: string | null
}

export type AgentsRow = {
  id: string
  workspace_id: string
  character_id: string
  role: 'ceo' | 'character' | 'trend_research' | 'creative_director' | 'content_planner' | 'copywriter' | 'image_prompt' | 'video_script' | 'quality' | 'safety' | 'publishing' | 'community' | 'growth_analyst' | 'sales' | 'finance_analyst'
  name: string
  status: 'disabled' | 'active' | 'paused'
  autonomy: 'suggest_only' | 'approval_required' | 'autonomous_within_limits'
  config: Json
  daily_budget_usd: number
  max_actions_per_day: number
  last_run_at: string | null
  created_at: string
  updated_at: string
}

export type AnalyticsDailyRow = {
  id: string
  workspace_id: string
  character_id: string
  social_account_id: string
  platform: string
  day: string
  followers: number | null
  following: number | null
  reach: number | null
  impressions: number | null
  views: number | null
  likes: number | null
  comments: number | null
  shares: number | null
  saves: number | null
  profile_visits: number | null
  link_clicks: number | null
  source: 'platform_api' | 'manual_import'
  captured_at: string
}

export type AudienceMetricsRow = {
  id: string
  workspace_id: string
  social_account_id: string
  day: string
  dimension: 'age' | 'gender' | 'country' | 'city' | 'language' | 'device'
  bucket: string
  value: number
  source: 'platform_api' | 'manual_import'
  captured_at: string
}

export type AuditLogRow = {
  id: string
  workspace_id: string | null
  actor_type: 'user' | 'agent' | 'system'
  actor_id: string | null
  action: string
  entity_type: string | null
  entity_id: string | null
  outcome: 'success' | 'denied' | 'error'
  details: Json
  created_at: string
}

export type BrandContactsRow = {
  id: string
  workspace_id: string
  brand_name: string
  full_name: string | null
  email: string | null
  role_title: string | null
  phone: string | null
  website: string | null
  consent_basis: 'published_business_contact' | 'inbound' | 'referral' | 'existing_relationship'
  do_not_contact: boolean
  opted_out_at: string | null
  notes: string | null
  created_at: string
  updated_at: string
}

export type BrandDealsRow = {
  id: string
  workspace_id: string
  character_id: string
  lead_id: string | null
  contact_id: string | null
  campaign_id: string | null
  title: string
  status: 'negotiating' | 'contracted' | 'in_production' | 'delivered' | 'invoiced' | 'paid' | 'cancelled'
  value_cents: number
  currency: string
  deliverables: Json
  usage_rights: string | null
  exclusivity_until: string | null
  disclosure_required: boolean
  start_date: string | null
  due_date: string | null
  invoiced_at: string | null
  paid_at: string | null
  created_at: string
  updated_at: string
}

export type CampaignContentRow = {
  workspace_id: string
  campaign_id: string
  content_item_id: string
  created_at: string
}

export type CampaignsRow = {
  id: string
  workspace_id: string
  character_id: string | null
  name: string
  objective: string | null
  type: 'growth' | 'sponsorship' | 'launch' | 'affiliate' | 'evergreen' | 'other'
  status: 'draft' | 'active' | 'paused' | 'completed' | 'cancelled'
  start_date: string | null
  end_date: string | null
  budget_cents: number | null
  currency: string
  created_by: string | null
  created_at: string
  updated_at: string
}

export type CharacterAssetsRow = {
  id: string
  workspace_id: string
  character_id: string
  kind: 'avatar' | 'reference_image' | 'style_guide' | 'voice_sample' | 'logo' | 'consent_evidence' | 'other'
  storage_bucket: 'character-assets' | 'reference-images'
  storage_path: string
  file_name: string
  mime_type: string
  bytes: number
  width: number | null
  height: number | null
  sha256: string | null
  provenance: 'owned' | 'licensed' | 'ai_generated'
  rights_notes: string | null
  depicts_real_person: boolean
  consent_evidence_path: string | null
  is_primary: boolean
  status: 'pending_upload' | 'ready' | 'deleted'
  uploaded_by: string | null
  created_at: string
  updated_at: string
}

export type CharacterBrandRulesRow = {
  id: string
  workspace_id: string
  character_id: string
  rule_type: 'do' | 'dont' | 'voice' | 'topic_allowed' | 'topic_blocked' | 'hashtag' | 'cta' | 'brand_safety'
  rule: string
  priority: number
  active: boolean
  created_at: string
  updated_at: string
}

export type CharacterFinancialsRow = {
  workspace_id: string | null
  character_id: string | null
  currency: string | null
  revenue_cents: number | null
  expense_cents: number | null
  profit_cents: number | null
}

export type CharacterMemoriesRow = {
  id: string
  workspace_id: string
  character_id: string
  kind: 'fact' | 'preference' | 'event' | 'relationship' | 'catchphrase' | 'continuity'
  content: string
  importance: number
  source: 'owner' | 'agent' | 'content'
  source_ref: string | null
  is_canon: boolean
  confirmed_by: string | null
  confirmed_at: string | null
  agent_run_id: string | null
  created_at: string
  updated_at: string
}

export type CharacterProfilesRow = {
  id: string
  workspace_id: string
  character_id: string
  display_name: string
  description: string | null
  niche: string | null
  target_audience: string | null
  personality: Json
  tone_of_voice: string | null
  backstory: string | null
  content_boundaries: Json
  platform_strategy: Json
  monetisation_strategy: Json
  language: string
  version: number
  created_at: string
  updated_at: string
}

export type CharacterVisualRulesRow = {
  id: string
  workspace_id: string
  character_id: string
  appearance_description: string | null
  style_keywords: string[]
  color_palette: string[]
  camera_style: string | null
  prompt_prefix: string | null
  negative_prompt: string | null
  do_not_depict: string[]
  created_at: string
  updated_at: string
}

export type CharactersRow = {
  id: string
  workspace_id: string
  name: string
  slug: string
  status: 'draft' | 'active' | 'paused' | 'archived'
  ai_disclosure_mode: 'always' | 'bio_and_posts' | 'bio_only'
  disclosure_text: string
  approval_mode: 'human_required' | 'auto_low_risk'
  min_audience_age: number
  age_restricted: boolean
  depicts_real_person: boolean
  consent_evidence_path: string | null
  content_policy_id: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

export type ContentAssetsRow = {
  id: string
  workspace_id: string
  character_id: string
  content_item_id: string | null
  kind: 'image' | 'video' | 'audio' | 'thumbnail' | 'document'
  storage_bucket: 'generated-content' | 'campaign-assets'
  storage_path: string
  mime_type: string
  bytes: number | null
  width: number | null
  height: number | null
  duration_seconds: number | null
  provenance: 'ai_generated' | 'uploaded'
  generation_provider: string | null
  prompt: string | null
  agent_run_id: string | null
  status: 'pending' | 'ready' | 'failed' | 'deleted'
  created_at: string
  updated_at: string
}

export type ContentCalendarRow = {
  id: string
  workspace_id: string
  character_id: string
  platform: string
  slot_date: string
  slot_time: string | null
  timezone: string
  content_item_id: string | null
  note: string | null
  status: 'planned' | 'filled' | 'skipped'
  created_at: string
  updated_at: string
}

export type ContentIdeasRow = {
  id: string
  workspace_id: string
  character_id: string
  campaign_id: string | null
  title: string
  summary: string | null
  angle: string | null
  platforms: string[]
  source: 'owner' | 'agent'
  agent_run_id: string | null
  status: 'new' | 'accepted' | 'rejected' | 'converted'
  score: number | null
  trend_refs: Json
  created_by: string | null
  created_at: string
  updated_at: string
}

export type ContentItemsRow = {
  id: string
  workspace_id: string
  character_id: string
  campaign_id: string | null
  idea_id: string | null
  platform: string
  format: 'post' | 'carousel' | 'reel' | 'short' | 'story' | 'thread' | 'video' | 'live_script'
  title: string
  status: 'draft' | 'in_review' | 'approved' | 'rejected' | 'scheduled' | 'publishing' | 'published' | 'failed' | 'archived'
  current_version: number
  is_sponsored: boolean
  content_rating: 'general' | 'teen' | 'mature'
  safety_status: 'unchecked' | 'passed' | 'flagged' | 'blocked'
  safety_report: Json
  disclosure_applied: boolean
  approval_id: string | null
  agent_run_id: string | null
  scheduled_for: string | null
  timezone: string
  published_at: string | null
  created_by: string | null
  created_at: string
  updated_at: string
  brand_deal_id: string | null
}

export type ContentMetricsRow = {
  id: string
  workspace_id: string
  content_item_id: string
  social_account_id: string
  platform: string
  day: string
  views: number | null
  reach: number | null
  impressions: number | null
  likes: number | null
  comments: number | null
  shares: number | null
  saves: number | null
  link_clicks: number | null
  watch_time_seconds: number | null
  avg_view_duration_s: number | null
  source: 'platform_api' | 'manual_import'
  captured_at: string
}

export type ContentPoliciesRow = {
  id: string
  workspace_id: string
  name: string
  version: number
  is_default: boolean
  rules: Json
  created_by: string | null
  created_at: string
  updated_at: string
}

export type ContentVersionsRow = {
  id: string
  workspace_id: string
  content_item_id: string
  version: number
  caption: string | null
  script: string | null
  hashtags: string[]
  image_prompt: string | null
  video_prompt: string | null
  metadata: Json
  created_by_type: 'user' | 'agent'
  created_by: string | null
  agent_run_id: string | null
  created_at: string
}

export type EngagementItemsRow = {
  id: string
  workspace_id: string
  character_id: string
  social_account_id: string
  platform: string
  kind: 'comment' | 'mention' | 'dm' | 'reply'
  external_id: string
  parent_external_id: string | null
  content_item_id: string | null
  author_handle: string | null
  author_external_id: string | null
  body: string
  received_at: string
  status: 'new' | 'needs_reply' | 'replied' | 'ignored' | 'hidden' | 'escalated'
  moderation_status: 'unchecked' | 'ok' | 'flagged' | 'blocked'
  moderation_labels: Json
  created_at: string
  updated_at: string
}

export type EngagementRepliesRow = {
  id: string
  workspace_id: string
  engagement_item_id: string
  body: string
  is_ai_generated: boolean
  status: 'suggested' | 'awaiting_approval' | 'approved' | 'rejected' | 'sent' | 'failed'
  approval_id: string | null
  agent_run_id: string | null
  sent_at: string | null
  external_id: string | null
  error: string | null
  created_at: string
  updated_at: string
}

export type ExpensesRow = {
  id: string
  workspace_id: string
  character_id: string | null
  campaign_id: string | null
  category: 'ai_compute' | 'software' | 'ads' | 'production' | 'contractor' | 'fees' | 'other'
  vendor: string | null
  amount_cents: number
  currency: string
  occurred_on: string
  description: string | null
  receipt_path: string | null
  agent_run_id: string | null
  created_at: string
  updated_at: string
}

export type GodStatusRow = {
  id: number
  thought: string | null
  meta: Json | null
  intent: Json | null
  updated_at: string
}

export type IntegrationConnectionsRow = {
  id: string
  workspace_id: string
  provider: string
  kind: 'ai_text' | 'ai_image' | 'ai_video' | 'ai_moderation' | 'ai_embeddings' | 'payments' | 'email' | 'analytics' | 'other'
  status: 'not_configured' | 'configured' | 'verified' | 'error' | 'disabled'
  config: Json
  last_checked_at: string | null
  last_error: string | null
  created_at: string
  updated_at: string
}

export type LeadsRow = {
  id: string
  workspace_id: string
  character_id: string | null
  contact_id: string | null
  brand_name: string
  website: string | null
  stage: 'prospect' | 'researched' | 'pitched' | 'replied' | 'negotiating' | 'won' | 'lost'
  stage_changed_at: string
  fit_score: number | null
  fit_reasoning: string | null
  fit_signals: Json
  source: 'manual' | 'csv' | 'inbound' | 'agent_research' | 'referral'
  estimated_value_cents: number | null
  next_action: string | null
  next_action_at: string | null
  lost_reason: string | null
  notes: string | null
  created_at: string
  updated_at: string
}

export type ProductsRow = {
  id: string
  workspace_id: string
  character_id: string | null
  name: string
  kind: 'digital' | 'physical' | 'service' | 'membership'
  price_cents: number | null
  currency: string
  status: 'draft' | 'active' | 'retired'
  external_ref: string | null
  created_at: string
  updated_at: string
}

export type PublishingJobsRow = {
  id: string
  workspace_id: string
  content_item_id: string
  social_account_id: string
  platform: string
  scheduled_for: string
  timezone: string
  status: 'pending' | 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled' | 'blocked'
  approval_id: string | null
  auto_approved_reason: string | null
  idempotency_key: string
  attempts: number
  max_attempts: number
  next_attempt_at: string | null
  locked_at: string | null
  last_error: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

export type PublishingPoliciesRow = {
  id: string
  workspace_id: string
  platform: string
  publishing_enabled: boolean
  requires_human_approval: boolean
  max_posts_per_day: number
  min_minutes_between_posts: number
  ai_label_required: boolean
  sponsored_disclosure_required: boolean
  created_at: string
  updated_at: string
  character_id: string | null
  auto_publish_allowed: boolean
}

export type PublishingResultsRow = {
  id: string
  workspace_id: string
  publishing_job_id: string
  attempt: number
  status: 'success' | 'failure'
  external_post_id: string | null
  url: string | null
  response_summary: Json
  error: string | null
  created_at: string
}

export type RevenueRow = {
  id: string
  workspace_id: string
  character_id: string | null
  source_type: 'affiliate' | 'sponsorship' | 'product' | 'subscription' | 'tips' | 'licensing' | 'platform_payout' | 'other'
  brand_deal_id: string | null
  affiliate_link_id: string | null
  product_id: string | null
  campaign_id: string | null
  amount_cents: number
  currency: string
  occurred_on: string
  status: 'expected' | 'pending' | 'received' | 'refunded'
  external_ref: string | null
  description: string | null
  created_at: string
  updated_at: string
}

export type SocialAccountsRow = {
  id: string
  workspace_id: string
  character_id: string
  platform: string
  handle: string | null
  display_name: string | null
  external_account_id: string | null
  status: 'disconnected' | 'pending' | 'connected' | 'error' | 'revoked'
  scopes: string[]
  connected_at: string | null
  last_synced_at: string | null
  last_error: string | null
  created_at: string
  updated_at: string
}

export type SocialCredentialsMetadataRow = {
  id: string
  workspace_id: string
  social_account_id: string
  token_type: 'oauth2' | 'oauth1' | 'api_key'
  scopes: string[]
  expires_at: string | null
  refresh_expires_at: string | null
  key_version: string
  last_refreshed_at: string | null
  status: 'valid' | 'expired' | 'revoked' | 'refresh_failed'
  created_at: string
  updated_at: string
}

export type SubscribersRow = {
  id: string
  email: string
  source: string | null
  referrer: string | null
  confirmed: boolean
  unsubscribed_at: string | null
  created_at: string
}

export type TodosRow = {
  id: string
  title: string
  description: string | null
  status: 'proposed' | 'pending' | 'in_progress' | 'completed' | 'failed' | 'blocked' | 'vetoed'
  priority: 'low' | 'medium' | 'high' | 'critical'
  assigned_agent: string | null
  is_boss: boolean
  deadline: string | null
  comments: TodoComment[]
  retry_count: number
  metadata: Json | null
  parent_task_id: string | null
  task_category: 'db' | 'ui' | 'infra' | 'analysis' | 'other'
  created_at: string
  updated_at: string
}

export type TracesRow = {
  id: string
  task_id: string | null
  agent_name: string | null
  tool_name: string
  input_summary: string | null
  result_summary: string | null
  duration_ms: number | null
  is_error: boolean
  created_at: string
}

export type WebhookEventsRow = {
  id: string
  workspace_id: string | null
  provider: string
  event_id: string
  event_type: string | null
  signature_valid: boolean
  payload: Json
  status: 'received' | 'processed' | 'ignored' | 'failed'
  error: string | null
  received_at: string
  processed_at: string | null
}

export type WorkspaceMembersRow = {
  workspace_id: string
  user_id: string
  role: 'owner' | 'admin' | 'editor' | 'viewer'
  created_at: string
  updated_at: string
}

export type WorkspacesRow = {
  id: string
  name: string
  owner_id: string
  created_at: string
  updated_at: string
}

type Table<Row, Required extends keyof Row> = {
  Row: Row
  Insert: Pick<Row, Required> & Partial<Omit<Row, Required>>
  Update: Partial<Row>
  Relationships: []
}

export interface Database {
  __InternalSupabase: { PostgrestVersion: '12' }
  public: {
    Tables: {
      affiliate_links: Table<AffiliateLinksRow, 'workspace_id' | 'program' | 'destination_url'>
      agent_approvals: Table<AgentApprovalsRow, 'workspace_id' | 'action_type' | 'entity_type' | 'title' | 'requested_by_type'>
      agent_run_events: Table<AgentRunEventsRow, 'workspace_id' | 'agent_run_id' | 'seq' | 'type'>
      agent_runs: Table<AgentRunsRow, 'workspace_id' | 'agent_task_id' | 'agent_id' | 'character_id'>
      agent_tasks: Table<AgentTasksRow, 'workspace_id' | 'character_id' | 'agent_id' | 'type' | 'title'>
      agents: Table<AgentsRow, 'workspace_id' | 'character_id' | 'role' | 'name'>
      analytics_daily: Table<AnalyticsDailyRow, 'workspace_id' | 'character_id' | 'social_account_id' | 'platform' | 'day' | 'source'>
      audience_metrics: Table<AudienceMetricsRow, 'workspace_id' | 'social_account_id' | 'day' | 'dimension' | 'bucket' | 'value' | 'source'>
      audit_log: Table<AuditLogRow, 'actor_type' | 'action'>
      brand_contacts: Table<BrandContactsRow, 'workspace_id' | 'brand_name' | 'consent_basis'>
      brand_deals: Table<BrandDealsRow, 'workspace_id' | 'character_id' | 'title'>
      campaign_content: Table<CampaignContentRow, 'workspace_id' | 'campaign_id' | 'content_item_id'>
      campaigns: Table<CampaignsRow, 'workspace_id' | 'name'>
      character_assets: Table<CharacterAssetsRow, 'workspace_id' | 'character_id' | 'kind' | 'storage_bucket' | 'storage_path' | 'file_name' | 'mime_type' | 'bytes' | 'provenance'>
      character_brand_rules: Table<CharacterBrandRulesRow, 'workspace_id' | 'character_id' | 'rule_type' | 'rule'>
      character_memories: Table<CharacterMemoriesRow, 'workspace_id' | 'character_id' | 'kind' | 'content'>
      character_profiles: Table<CharacterProfilesRow, 'workspace_id' | 'character_id' | 'display_name'>
      character_visual_rules: Table<CharacterVisualRulesRow, 'workspace_id' | 'character_id'>
      characters: Table<CharactersRow, 'workspace_id' | 'name' | 'slug'>
      content_assets: Table<ContentAssetsRow, 'workspace_id' | 'character_id' | 'kind' | 'storage_bucket' | 'storage_path' | 'mime_type' | 'provenance'>
      content_calendar: Table<ContentCalendarRow, 'workspace_id' | 'character_id' | 'platform' | 'slot_date'>
      content_ideas: Table<ContentIdeasRow, 'workspace_id' | 'character_id' | 'title'>
      content_items: Table<ContentItemsRow, 'workspace_id' | 'character_id' | 'platform' | 'format' | 'title'>
      content_metrics: Table<ContentMetricsRow, 'workspace_id' | 'content_item_id' | 'social_account_id' | 'platform' | 'day' | 'source'>
      content_policies: Table<ContentPoliciesRow, 'workspace_id' | 'name'>
      content_versions: Table<ContentVersionsRow, 'workspace_id' | 'content_item_id' | 'version' | 'created_by_type'>
      engagement_items: Table<EngagementItemsRow, 'workspace_id' | 'character_id' | 'social_account_id' | 'platform' | 'kind' | 'external_id' | 'body' | 'received_at'>
      engagement_replies: Table<EngagementRepliesRow, 'workspace_id' | 'engagement_item_id' | 'body'>
      expenses: Table<ExpensesRow, 'workspace_id' | 'category' | 'amount_cents' | 'occurred_on'>
      god_status: Table<GodStatusRow, never>
      integration_connections: Table<IntegrationConnectionsRow, 'workspace_id' | 'provider' | 'kind'>
      leads: Table<LeadsRow, 'workspace_id' | 'brand_name'>
      products: Table<ProductsRow, 'workspace_id' | 'name' | 'kind'>
      publishing_jobs: Table<PublishingJobsRow, 'workspace_id' | 'content_item_id' | 'social_account_id' | 'platform' | 'scheduled_for' | 'idempotency_key'>
      publishing_policies: Table<PublishingPoliciesRow, 'workspace_id' | 'platform'>
      publishing_results: Table<PublishingResultsRow, 'workspace_id' | 'publishing_job_id' | 'attempt' | 'status'>
      revenue: Table<RevenueRow, 'workspace_id' | 'source_type' | 'amount_cents' | 'occurred_on'>
      social_accounts: Table<SocialAccountsRow, 'workspace_id' | 'character_id' | 'platform'>
      social_credentials_metadata: Table<SocialCredentialsMetadataRow, 'workspace_id' | 'social_account_id'>
      subscribers: Table<SubscribersRow, 'email'>
      todos: Table<TodosRow, 'title'>
      traces: Table<TracesRow, 'tool_name'>
      webhook_events: Table<WebhookEventsRow, 'provider' | 'event_id' | 'signature_valid'>
      workspace_members: Table<WorkspaceMembersRow, 'workspace_id' | 'user_id' | 'role'>
      workspaces: Table<WorkspacesRow, 'name' | 'owner_id'>
    }
    Views: {
      character_financials: { Row: CharacterFinancialsRow; Relationships: [] }
    }
    Functions: {
      current_user_is_platform_admin: { Args: Record<string, never>; Returns: boolean }
      sync_platform_admin: { Args: { p_user_id: string; p_is_admin: boolean }; Returns: undefined }
      claim_agent_tasks: { Args: { p_limit?: number }; Returns: AgentTaskRow[] }
      claim_publishing_jobs: { Args: { p_limit?: number }; Returns: PublishingJobRow[] }
      complete_publishing_job: {
        Args: { p_job_id: string; p_success: boolean; p_external_post_id?: string | null; p_url?: string | null; p_error?: string | null; p_response?: Json }
        Returns: PublishingJobRow
      }
      reap_stuck_publishing_jobs: { Args: { p_older_than?: string }; Returns: number }
      store_social_credential: { Args: { p_social_account_id: string; p_ciphertext: string }; Returns: undefined }
      read_social_credential: { Args: { p_social_account_id: string }; Returns: string | null }
      delete_social_credential: { Args: { p_social_account_id: string }; Returns: undefined }
    }
    Enums: { [_ in never]: never }
    CompositeTypes: { [_ in never]: never }
  }
}

export type TableName = keyof Database['public']['Tables']
export type Tables<T extends TableName> = Database['public']['Tables'][T]['Row']
export type TablesInsert<T extends TableName> = Database['public']['Tables'][T]['Insert']
export type TablesUpdate<T extends TableName> = Database['public']['Tables'][T]['Update']

// Convenience aliases used across the app.
export type WorkspaceRole = WorkspaceMembersRow['role']
export type AgentRole = AgentsRow['role']
export type AgentRow = AgentsRow
export type CharacterRow = CharactersRow
export type TodoRow = TodosRow
export type TraceRow = TracesRow
export type PublishingJobRow = PublishingJobsRow
export type AgentTaskRow = AgentTasksRow
export type PublishingPolicyRow = PublishingPoliciesRow
/** Platforms with built-in providers (the schema accepts any registered provider id). */
export type SocialPlatform = 'instagram' | 'tiktok' | 'youtube' | 'x'
